version: "3.7"
services:
  app:
    build:
      args:
        DOCKER_PHP_VERSION: '8.1'
        user: ${UNIX_USER}
        uid: ${UNIX_UID}
      context: ./
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
        - ./.docker/mongodb/db:/data/db
        - ./.docker/mongodb/dev.archive:/Databases/dev.archive
        - ./.docker/mongodb/production:/Databases/production
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
